version: "3"
services:
  initial-data-load-service:
    build:
      context: ./initial-data-load
    command: yarn start
    ports:
      - 8082:8082
    environment:
      MONGO_URI: ${MONGO_URI}
      DB_NAME: ${DB_NAME}
      # postgis connection
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # default Azurite connection string from documentation for local development
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
      DATASET: ${DATASET}
      COUNTRY: ${COUNTRY}
      UPLOAD_DATA_TYPES: ${UPLOAD_DATA_TYPES}
      NEW_STORAGE_CONTAINERS: ${NEW_STORAGE_CONTAINERS}
      NEW_STORAGE_QUEUES: ${NEW_STORAGE_QUEUES}
      AZURE_STORAGE_LAYER_CONTAINER_NAME: ${AZURE_STORAGE_LAYER_CONTAINER_NAME}
      BOTTLENECK_MAX_CONCURRENT: ${BOTTLENECK_MAX_CONCURRENT}
      BOTTLENECK_TIME_LIMIT: ${BOTTLENECK_TIME_LIMIT}
    depends_on:
      - azurite
    links:
      - azurite

  url-loader:
    build:
      context: ./url-loader
    volumes:
      - ./url-loader/src:/home/node/src
      - ./url-loader/index.js:/home/node/index.js
    command: yarn start
    ports:
      - 8083:8083
    environment:
      # default Azurite connection string from documentation for local development
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
      AZURE_STORAGE_DATA_CONTAINER_NAME: ${AZURE_STORAGE_DATA_CONTAINER_NAME}
      MONGO_URI: ${MONGO_URI}
      DB_NAME: ${DB_NAME}
      URL_FILE: ${URL_FILE}
      ONLY_SOURCE_NAMES: ${ONLY_SOURCE_NAMES}
      EXCEPT_SOURCE_NAMES: ${EXCEPT_SOURCE_NAMES}
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
    depends_on:
      - azurite
    links:
      - azurite

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    ports:
      - 10000:10000
      - 10001:10001
    restart: always
