const FEATURE_ATTRIBUTES_COLLECTION_NAME = 'featureAttributes';
const POINT_ATTRIBUTES_COLLECTION_NAME = 'pointAttributes';

module.exports = {
  FEATURE_ATTRIBUTES_COLLECTION_NAME,
  POINT_ATTRIBUTES_COLLECTION_NAME,
};
