version: '3.2'
services:
  test-db:
    image: mongo
    hostname: test-db
    ports:
      - 27917:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8181:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: test-db

  api-test-app:
    container_name: api-test-app
    build:
      context: .
      args:
        NODE_ENV: test
    restart: on-failure
    environment:
      MONGO_URI: mongodb://test-db:27017/oscar
    command: yarn test
